In [1]:
import pandas as pd
import numpy as np
import nltk

import matplotlib.pyplot as plt
import matplotlib as mpl

import seaborn as sns
sns.set()

%matplotlib inline

In [56]:
russia_df = pd.read_csv('csvs/km_tfidf.csv', index_col = 'tweet_id')
del russia_df['Unnamed: 0']
russia_df.sample(2)

,text,cluster_k3,cluster_k4,cluster_k5,cluster_k6,cluster_k7,cluster_k8,cluster_k9,cluster_k10,cluster_k11,cluster_k12,cluster_k13,cluster_k14,cluster_k15,cluster_k16,cluster_k17,cluster_k18,cluster_k19,cluster_k25,cluster_k30
tweet_id,,,,,,,,,,,,,,,,,,,,
7.681472e+17,Today's fashion look https://t.co/iC8WXgTEz4,0,1,0,2,3,1,0,6,7,1,6,4,6,0,14,0,14,0,1
8.340178e+17,RIP Germany https://t.co/smcQh9N52l,1,1,0,2,3,1,0,6,7,1,6,4,6,0,14,0,14,0,1

In [147]:
k = 0
cluster_tweets = russia_df[russia_df['cluster_k14'] == k]
print (cluster_tweets.sample(5)['text'].values)
print('Size: {}'.format(len(cluster_tweets)))

['Wir machen Schluss mit neuen Schulden #Merkelmussbleiben'
 'Die Wirtschaft von USA zwingt Merkel zu einer Freudschaft, das freut mich aber #TTIP #Merkelmussbleiben'
 'Deutschland ohne #NATO-Mitgliedschaft existiert nicht! #Merkelmussbleiben Tagebuch'
 'Nach dem\xa0Anschlag von #Nizza hat #Merkel\xa0ihr Beileid ausgesprochen. Brav gemacht! #Merkelmussbleiben'
 'Jetzt sehe ich keine Alternative f√ºr sie #Merkelmussbleiben']
Size: 1472